name: Backend Deploy

on:
  push:
    paths:
      - 'resume-counter/**'
      - '!resume-counter/updateVisitorCount/index.js'
      - '!resume-counter/updateVisitorCountPython/test_*.py'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r resume-counter/updateVisitorCountPython/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest resume-counter/updateVisitorCountPython/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group cloud-resume-rg \
            --template-file resume-counter/infra/template.json \
            --parameters @resume-counter/infra/parameters.json
