name: Azure Function Python CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'updateVisitorCountPython/**'
      - 'infra/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CI/CD trigger reached
        run: echo "🎯 Reached CI/CD workflow"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r resume-counter/updateVisitorCountPython/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest resume-counter/updateVisitorCountPython/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: cloud-resume-rg
          template: ./infra/template.json
          parameters: ./infra/parameters.json

      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: resumecounter-func
          package: ./resume-counter/updateVisitorCountPython

      - name: Echo backend-deploy workflow is running
        run: echo "✅ CI/CD backend-deploy workflow is running"
